name: Test Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: oven-sh/setup-bun@v1
       - run: npm install pnpm
       - run: pnpm install
       - run: pnpm run build